apiVersion: v1
kind: Service
metadata:
  name: secret-service
  namespace: $namespace
spec:
  type: LoadBalancer
  ports:
    - name: secret-port
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    name: secret-pod
